apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todolist-pvc-data
  namespace: todoapp
spec:
  volumeName: todolist-pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
